version: '3'
services:
  mysql:
    image: mariadb:10.4.7
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oauth_login_tutorial
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  login-api:
    container_name: login-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/chit-chat/run.sh
      - ./login-api/build/libs:/home/chit-chat/libs
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
    command: bash -c "cd /home/chit-chat && sh run.sh"
  login-web:
    container_name: login-web
    image: node:16.13.2
    volumes:
      - ./login-web:/home/chit-chat
    ports:
      - 3000:3000
    expose:
      - 3000
    command: bash -c "cd /home/chit-chat && npm run dev"
    healthcheck:
      test: curl -sS http://localhost:3000 || exit 1
      timeout: 10s
      retries: 10