version: '3'
services:
  mysql:
    image: mariadb:10.4.7
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oauth_login_tutorial
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  chit-chat-login-api:
    container_name: chit-chat-login-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/chit-chat/run.sh
      - ./chit-chat-login-api/build/libs:/home/chit-chat/libs
    expose:
      - 8080
    depends_on:
      - mysql
    command: bash -c "cd /home/chit-chat && sh run.sh"
  chit-chat-user-api:
    container_name: chit-chat-user-api
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/chit-chat/run.sh
      - ./chit-chat-user-api/build/libs:/home/chit-chat/libs
    expose:
      - 8080
    depends_on:
      - mysql
    command: bash -c "cd /home/chit-chat && sh run.sh"
  chit-chat-nginx:
    container_name: chit-chat-nginx
    image: nginx
    depends_on:
      - chit-chat-login-api
      - chit-chat-user-api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/build:/home